spring:
  profiles:
    active: ${profile}

  # Multipart request 설정
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB

  # JSON 네이밍 전역 설정 (snake_type)
  jackson:
    property-naming-strategy: SNAKE_CASE

# S3 Properties
aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}
    image-url: https://${S3_BUCKET_NAME}.s3.${S3_REGION}.amazonaws.com/
